### ISSUE TITLE
No rule to make target `test'.

### ISSUE THREAD

**Issue by kg0r0** [hyperledger/ursa-wrapper-go#20]
**What I'm trying to do**

Run test for development.
I ran the following command as described in the [README](https://github.com/hyperledger/ursa-wrapper-go#development).

```
make test
```

**Expected result**

Run unit tests.

**Actual result**

I get the following error:
```
make: *** No rule to make target `test'.  Stop.
```
This is because the target in the Makefile is "unit-test", not "test".
https://github.com/hyperledger/ursa-wrapper-go/blob/main/Makefile#L5

**Sample code / test case**

Execute the following command.
```
make unit-test
```
I recommend modifying the Makefile or README.
Let me fix it if you like.

**Comment by abbos1711** [comment]
Too i can't used  this command :  "make run"  .  How i solve this problem ?
